# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'liberica'
#        cache: maven
    - name: Build with Maven
      # run: mvn -B package --file pom.xml
      run: mvn checkstyle:checkstyle


#  install_chrome:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'liberica'
#      #        cache: maven
#      - name: install chrome
#        # run: mvn -B package --file pom.xml
#        run: |
#              curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip" \
#              && cd /tmp \
#              && unzip chromedriver_linux64.zip \
#              && rm -rf chromedriver_linux64.zip \
#              && sudo mv chromedriver /usr/local/bin/chromedriver \
#              && sudo chmod +x /usr/local/bin/chromedriver \
#              && chromedriver --version

  testing_UI:

      runs-on: ubuntu-latest

      needs: build_test

      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3

          with:
            java-version: '11'
            distribution: 'temurin'
        - run: mvn clean verify -pl modules/ui-functional-test -Dbrowser=chrome

  testing_API:

    runs-on: ubuntu-latest

    needs: build_test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: mvn clean verify -pl modules/api-functional-test